### ISSUE TITLE
Add Google Gemini API support

### ISSUE THREAD

**Issue by ckundo** [cartertemm/AI-content-describer#11]
I've been working on a similar add-on that uses Google Gemini vision APIs (see https://youtu.be/-zESXbEA160). Are you all considering adding a Gemini hook to your plugin?

**Comment by cartertemm** [comment]
What are your thoughts after using Google Gemini for some time? I know the pricing is comparable to GPT vision (if not cheaper). How about accuracy?

I hadn't considered implementing it before, but it could definitely be a good backup option.

**Comment by cartertemm** [comment]
Support for Google Gemini, Claude 3, and llama.cpp added.
