### ISSUE TITLE
update addon for new AI models

### ISSUE THREAD

**Issue by joshknnd1982** [cartertemm/AI-content-describer#37]
The addon is not compatible with new AI models such as gemini flash and llama-3.2 vision 11B parameter models

**Comment by MH140000** [comment]
and mistral vision

**Comment by cartertemm** [comment]
The latest version includes support for new Gemini models: pro vision, 1.5 flash (8B), and 1.5 pro, as well as Mistral's PixtralLarge.

Llama 3.2 vision will work when I add support for Ollama. I am looking into ways that it can be accessed remotely as well for those who do not have systems with the adequate specifications.

**Comment by cartertemm** [comment]
As of December 8, Ollama is now supported. You can select a model in the configuration panel. That model will be used whenever Ollama is set in the AIC context menu.

It probably goes without saying, but this is a beta feature. Things might not yet work in the way you expect.

Feel free to open issues as you encounter them.

Thanks for your patience as work has taken over my life! :)
