### ISSUE TITLE
Rendering Markdown

### ISSUE THREAD

**Issue by aaronr7734** [cartertemm/AI-content-describer#4]
There are many situations where I've had GPT4 create tables, organize text into headings and lists, etc. Yes, even for image descriptions.
Markdown is the most token efficient way to do this.
So I was wondering if for those of us using the browseableMessage if you could come up with a way to render this.

One way I've briefly explored is using Markdown (the python module) to convert GPT's output to html, then displaying that html via isHtml on the browseableMessage.
Thoughts?

**Comment by cartertemm** [comment]
This would be an easy feature to add, or first contribution if someone gets to it before I do. Tasks would include:

- Add clarification to the checkbox in settings, something like "Open each result in a browseable dialog, also renders HTML".
- Pass every result through `markdown.markdown`, which doesn't seem to raise an exception. Even on empty input, text is wrapped in a paragraph as we would expect so there is no need to check whether the response adheres to a certain format.
- Add `isHtml=True` to the call to `ui.browseableMessage`
- Mention as a feature in the readme
